### PR TITLE
formats: repair kexec

### PR DESCRIPTION
**Pull request by Lassulus**
no hardware to test right now. so if someone wants to test it, that would be helpful :)

### CODE REVIEW

**Review by benaryorg — CHANGES_REQUESTED** [review]
> no hardware to test right now

I usually just use qemu to boot up Ubuntu minimal (which other than Debian has a regular system under the hood) and then run kexec in there.

> so if someone wants to test it, that would be helpful

Commit 2ed5842458829312e5e05393f240bb4f05eea4a6 does build properly (i.e. `nix build .` does its thing).
When it comes to using *nixos-generate*, compared to previous versions, it seems that now I need to `lib.mkForce` the `services.openssh.settings.PermitRootLogin` option, so the transition is not 100% smooth.
Same applies to the `kexec.autoReboot` option which I had disabled before that does not seem to be present any more.

I've used [a minimal configuration for kexec](https://shell.cloud.bsocat.net/infra/raw/572f70e82adfb8d9e115bd3bf873ed1162ea1bfb/snippet/minimal-kexec.nix) (minor modifications for the above changes already incorporated) and the result when kexecing is this (even if the correct cmdline is provided):

```log
mounting tmpfs on /...
mounting ../nix-store.squashfs on /nix/.ro-store...
[    0.975880] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.976394] ../nix-store.squashfs: Can't open blockdev
mount: mounting ../nix-store.squashfs on /mnt-root/nix/.ro-store failed: No such file or directory

An error occurred in stage 1 of the boot process, which must mount the
root filesystem on `/mnt-root' and then start stage 2.  Press one
of the following keys:

  r) to reboot immediately
  *) to ignore the error and continue
```

A [hydra build for kexec using the nixos-generators flake](https://nixos-builder.cloud.bsocat.net/hydra/job/infra/nixos-generators/kexec-image#tabs-status) is currently succeeding but yields the same result ([NAR containing the tarball](https://nixos-builder.cloud.bsocat.net/nar/g3x685x7f5afhy3ccn3fybhw04wwrbi5.nar)) when executed.

**Comment by benaryorg** [comment]
After double checking that I didn't overlook anything, the error is indeed because the code introduced in this pull request does not in fact pull in a new initrd image rather than reuse the default initrd used for booting NixOS systems. That default image has no reference to the system that it's supposed to boot however. The previous code achieved this by using the [upstream netboot initrd](https://github.com/cleverca22/nix-tests/blob/2ba968302208ff0c17d555317c11fd3f06e947e2/kexec/kexec.nix#L8C32-L8C46) which does contain a full NixOS system generated from the corresponding configuration.

Since upstream does support building the kexec tree already using `config.system.build.kexecTree` my suggestion would be to include the functionality that was already present before, such as the *autoreboot* or *justdoit* modules, while replacing the `kexec_tarball` (referencing `<nixpkgs>`, the reason for it being broken in the first place) with the upstream version and some glue code that builds a tarball from the upstream version.
Note that this would either require an upstream contribution for the *clever-tests* to be usable as a flake directly, or the flake for *nixos-generators* to include the repository as a non-flake flake input which would allow referencing the specific files in there without having to copy or reimplement them (read: an additional dependency in the flake of this repository).

Alternatively said functionality could be dropped, which would slim down *nixos-generators*' job in the kexec matter a mere command line interface to the upstream *kexecTree* with a little bit of glue code to generate the tar from it. Personally I think that while that would be a lot less maintenance overhead, it'd also remove functionality that adds value, at least for those who are using the *justdoit* components, plus it'd be a breaking change as configurations using said values won't evaluate any more.

**Comment by IogaMaster** [comment]
It appears this pr is stale, I would like to fix this (I am going to by a raspberry pi  and would like to use nixos anywhere with it). Any idea how I could begin?

**Comment by Lassulus** [comment]
probably taking the relevant bits from here: https://github.com/nix-community/nixos-images/blob/main/nix/kexec-installer/module.nix

**Pull request closed without merging**
