### PR TITLE
qcow: enable biosboot only for x86

### PR DESCRIPTION
**Pull request by Lassulus**

### CODE REVIEW

**Comment by supermarin** [comment]
```
master $ nix build .#vm                                                                              dotfiles/nixos
warning: Git tree '/home/supermarin/dotfiles' is dirty
error:
       Failed assertions:
       - You must set the option ‘boot.loader.grub.devices’ or 'boot.loader.grub.mirroredBoots' to make the system bootable.
```

**Comment by Lassulus** [comment]
thanks, I just force pushed, can you test again?

**Comment by supermarin** [comment]
Tested - the build works, but can't boot into it. Gets into EFI shell and no grub. Am I doing something wrong?

**Comment by Lassulus** [comment]
hmm, weird, I guess I have to debug some more

**Comment by Lassulus** [comment]
alright, I added some changes again, would be nice if you could test it

**Comment by supermarin** [comment]
Looks good, :shipit:

**Pull request merged**
