### PR TITLE
qcow: add virtualisation.qemuImage.diskSize option

### PR DESCRIPTION
**Pull request by Kranzes**
~~This is very much a WIP PR, the new diskSize functionality does not even seem to work.~~ I created this PR to get other people's ideas and thoughts on this change,~~while also getting help on making this actually work.~~

I would also like to potentially make an option that will expose such diskSize options to the flake output options.

### CODE REVIEW

**Comment by Lassulus** [comment]
what exactly do you mean with does not seem to work? can you post some logs of what went wrong?

**Comment by Kranzes** [comment]
Sorry, it does actually work correctly. I have successfully crated 32gb and 16gb qcow images!

**Comment by Lassulus** [comment]
also such options should be added upstream. ideally we want the qcow.nix (or another file which includes it) to expose these options since they are more universally usable than in nixos-generators alone :)

**Comment by Kranzes** [comment]
I don't understand what you mean by adding it to upstream? How would this option work in nixpkgs?

**Comment by Lassulus** [comment]
for example like in this file: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/digital-ocean-image.nix#L12 maybe something like `virtualisation/qcow.nix` which defines this options and is then used by all the other image builders would be better?

**Comment by Kranzes** [comment]
I don't have any idea of other options for `virtualisation.qcow` so it seems a bit too much to create a whole file for it.

**Comment by Lassulus** [comment]
oh basically everything from https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-disk-image.nix like `additionalSpace` `bootSize` `partitionTableType` `fsType`

**Comment by Kranzes** [comment]
So I cooked this thing up https://github.com/NixOS/nixpkgs/pull/148186, could you please review it and add suggestions?

**Pull request closed without merging**
