### PR TITLE
Restore kexec

### PR DESCRIPTION
**Pull request by farcaller**
This restores kexec by vendoring the relevant bits of https://github.com/cleverca22/nix-tests. Verified bootable on hetzner bare metal.

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
Sorry for the long delay but now we got some actual error message:

```
this derivation will be built:
/nix/store/g3f603b1r9n27f5b1f4xbqasj2gxvnh9-tarball-tarball-.tar.xz.drv
building '/nix/store/g3f603b1r9n27f5b1f4xbqasj2gxvnh9-tarball-tarball-.tar.xz.drv'...
tarball-tarball> ln: failed to create symbolic link '/nix/store/xr5n6k6z6d1r1ih3iaspgw9ldmgzh0qy-tarball-tarball-.tar.xz' -> '': No such file or directory
error: builder for '/nix/store/g3f603b1r9n27f5b1f4xbqasj2gxvnh9-tarball-tarball-.tar.xz.drv' failed with exit code 1;
last 1 log lines:
> ln: failed to create symbolic link '/nix/store/xr5n6k6z6d1r1ih3iaspgw9ldmgzh0qy-tarball-tarball-.tar.xz' -> '': No such file or directory
For full logs, run 'nix log /nix/store/g3f603b1r9n27f5b1f4xbqasj2gxvnh9-tarball-tarball-.tar.xz.drv'.
```

**Comment by farcaller** [comment]
I'm not quite sure what the buildbot is doing there, but I ran `nix build` on 6fda344 and used the resulting nixos-generate to build a kexec-bundle with no issues just now.

**Comment by farcaller** [comment]
This seems to be coming from the "evaluate flakes" step that reports an incorrect derivation path.

> {"attr":"x86_64-linux.kexec","attrPath":["x86_64-linux","kexec"],"drvPath":"/nix/store/g3f603b1r9n27f5b1f4xbqasj2gxvnh9-tarball-tarball-.tar.xz.drv","inputDrvs":{"/nix/store/44cpbasxn94ka7ly2wg6r3rnv0zq7l7p-bash-5.2-p15.drv":["out"],"/nix/store/izcgbk3ckckzldqir2z8j96rm4ay72rb-tarball.drv":["out"],"/nix/store/llg3sc8gm2zvw1laflxs96sppc4ail3f-stdenv-linux.drv":["out"]},"isCached":false,"name":"kexec","outputs":{"out":"/nix/store/xr5n6k6z6d1r1ih3iaspgw9ldmgzh0qy-tarball-tarball-.tar.xz"},"system":"x86_64-linux"}

I don't know how the test for this repo are laid out, so I can't really fix it further. I don't thin the buildbot config is even part of the repo?

**Comment by Mic92** [comment]
Buildbot is testing the merge commit and not the commit of your branch. Otherwise I cannot tell what else would be different.

**Comment by farcaller** [comment]
Ah that's what is was! Thanks, I fixed the tests and I verified the build still works (as the build doesn't seem to exercise the same codepaths as the tests do for this case).

**Comment by Lassulus** [comment]
@mergify queue

**Comment by Lassulus** [comment]
thanks for fixing this!

**Pull request merged**
