### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by zimbatm**
A few misc cleanup changes

### CODE REVIEW

**Comment by Lassulus** [comment]
hmm, I can't run it right now
```
~/src/nixos-generators ./nixos-generate -f iso                                                                
error: cannot import '/nix/store/4s8vmgn195qnl6l6zp7ky1kvh22gfl1k-modules/installer/cd-dvd/iso-image.nix', since path '/nix/store/4s8vmgn195qnl6l6zp7ky1kvh22gfl1k-modules' is not valid, at /var/src/nixpkgs/lib/modules.nix:109:60
```

**Comment by zimbatm** [comment]
are you on nixos-unstable?

**Comment by Lassulus** [comment]
no I'm on stable

**Comment by zimbatm** [comment]
@Lassulus mind testing again with the latest change?

**Comment by Lassulus** [comment]
seems to work, thanks!

**Pull request merged**
