### PR TITLE
fix/cli idempotency

### PR DESCRIPTION
**Pull request by blaggacao**
- refactor: fix erroneus package naming
- fix: uniquely identiy the format-module

### CODE REVIEW

**Comment by blaggacao** [comment]
@Lassulus this went on to become a two commit PR fix on which `divnix/hive` has come to depend on. The renaming makes it so that nixos-generate is properly displayed in a `numtide/devshell`'s `menu`/MOTD.

The other fix works according to the comment. Preveously, module identity could not have been established which lead to conflict.

Now module identity can be established whenever the versions of nixos-generators align between the input used in a config and the input used in the CLI (and only then).

**Comment by Lassulus** [comment]
had to revert changes kinda in https://github.com/nix-community/nixos-generators/commit/41f3518bc194389df22a3d198215eae75e6b5ab9 since it introduces errors: https://github.com/nix-community/nixos-generators/issues/183

**Comment by blaggacao** [comment]
Maybe doing an `(import ./format-module.nix)` as part of the `imports` statement, would do... I'll check tomorrow.

**Comment by blaggacao** [comment]
@Lassulus this is better but let's have the OP confirm, first: https://github.com/nix-community/nixos-generators/pull/184

**Pull request merged**
