### PR TITLE
flake: export formats as nixosModules

### PR DESCRIPTION
**Pull request by Pacman99**
This project has some really cool modules that I want to make use of. I'd like to do it properly by getting them exported in this flake under `nixosModules`.

### CODE REVIEW

**Comment by Pacman99** [comment]
I guess this doesn't entirely make sense since using these modules would error out from the lack of a `formatAttr` and `filename` option.

**Comment by Lassulus** [comment]
huh dunno about flakes. not sure it makes sense to exports the internal modules?

**Comment by Pacman99** [comment]
Some of the formats are just modules outside of the `formatAttr` and `filename` options and they could be useful. For example someone could want to create a nixos system with the `do` module which ensures that that system can be used with digital ocean. And some of the other formats have more code that can be re-used.

**Comment by Pacman99** [comment]
Some more context for what we're planning downstream: https://github.com/divnix/digga/issues/49

**Pull request merged**
